### ISSUE TITLE
Establish patterns and structure

### ISSUE THREAD

**Issue by heathd** [alphagov/gds-tech-learning-pathway#1]
Before we invite the wider technology community to contribute we'd like to establish some patterns and structure for this repo.

Questions/issues:
- are 'guides' the right name?

User stories:
- Be able to find the right learning when they know what they want to learn
- be able to browse the things which they could learn for inspiration
- keep individual names private (ie, list of mentors etc should be stored elsewhere) - we intend to make this repo public
## Acceptance criteria
- we have a `CONTRIBUTING.md` setting out clearly how people should contribute

**Comment by MatMoore** [comment]
Is this issue still needed? Or can we split it up into smaller tasks?
