### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by nickcolley** [alphagov/gds-tech-learning-pathway#136]
"OK
error: Error processing app files: Error uploading application.
The resource file mode is invalid: File mode '0444' with path 'vendor/bundle/ruby/2.6.0/cache/bundler/git/middleman-search-dc03e8a4514245f371785a4aecb7aca5a5556c68/objects/pack/pack-c5c917e28bb27f9b0003f48e8e394bf501a88227.pack' is invalid. Minimum file mode is '0600'
Script failed with status 1"

https://travis-ci.com/alphagov/gds-tech-learning-pathway

**Comment by galund** [comment]
Going to dump the travis deployer and move into Concourse i.e. I'll make a PR against https://github.com/alphagov/tech-ops/blob/master/reliability-engineering/pipelines/internal-apps.yml

**Comment by galund** [comment]
Looks like this is WONTFIX; see discussion in Slack.
