### ISSUE TITLE
Add content on security

### ISSUE THREAD

**Issue by rboulton** [alphagov/gds-tech-learning-pathway#14]
Some notes from some conversations, with links to interesting resources:

- https://microcorruption.com/about  if you're interested in some of the lower level buffer overrun type stuff.
- http://cryptopals.com/  is fun for cryptanalysis stuff.
- we've used https://github.com/OWASP/railsgoat  for security workshops
- bandit levels from http://overthewire.org/wargames/
- https://alf.nu/alert1 - really good for understanding xss and injection attacks
- challenges on https://en.wikipedia.org/wiki/HackThisSite  . It's pretty good at giving a step by step intro (or at least I felt it was back in the day).

**Comment by MatMoore** [comment]
Might be some useful resources related to the security workshops we've run. Here are some of the trello boards:
https://trello.com/b/gvt4MUNF/security-workshop
https://trello.com/b/PmqWoOyy/security-workshop-2-planning

These workshops are being run continuously so we should definitely call them out as a thing. Topics we are going to cover this year are documented here: https://docs.google.com/spreadsheets/d/1B4Ii8w_wC1uDMdcvZDL4IIBVk4kwBJXv2XPk4jw1sw0/edit#gid=0 although I wouldn't link to that directly as it's an internal doc with names and stuff.

We've also run cross gov capture the flag events which is a great way to learn stuff. I don't know if we've blogged about this, all I can find is https://trello.com/c/wsbQmQi0/20-ruben-arakelyan-running-the-first-gds-capture-the-flag-competition
