### ISSUE TITLE
Write java guide

### ISSUE THREAD

**Issue by mrlumbu** [alphagov/gds-tech-learning-pathway#5]
This is a good resource https://github.com/cxxr/better-java

**Comment by heathd** [comment]
also this https://www.gitbook.com/book/ncrcoe/java-for-small-teams/details

**Comment by rboulton** [comment]
Free course for people with no programming experience (probably suitable for apprentices / maybe juniors) http://courses.caveofprogramming.com/p/java-for-complete-beginners

**Comment by MatMoore** [comment]
@mrlumbu I'm going to have a look at writing something for this during the firebreak this week. I'm about to move to a team that uses java, so hopefully the beginner's mindset will help, but would appreciate any pointers 😄

**Comment by MatMoore** [comment]
I've added the above resources, feel free to raise PRs if you want to extend it.
