### ISSUE TITLE
Change "beta" label to internal

### ISSUE THREAD

**Issue by MatMoore** [alphagov/gds-tech-learning-pathway#91]
Indicate that this is currently for GDS use, not wider government (at least the career path section of it), although external contributions are still welcome.

This is something that's been proposed for the [GDS way](https://gds-way.cloudapps.digital/) and we should follow suit if that changes.

**Comment by deborahchua** [comment]
https://github.com/alphagov/gds-tech-learning-pathway/pull/99

This has been pushed to the Paas
